### PR TITLE
Create an observer to set the provider and video id from the embed url, ...

### PR DESCRIPTION
**Pull request by xdumaine**
...and use them to embed the video with lazy-video

### CODE REVIEW

**Comment by xdumaine** [comment]
I also have a commit in here that resolves #14 - I meant to separate this out, my mistake. I'm used to bitbucket. I'll try to have fixes in separate PRs from now on. Let me know if you'd like me to separate that before merging anything.

**Comment by Dhaulagiri** [comment]
If you could separate it out that would be preferable. Reason being is that I have a pending PR in ember-lazy-video that would invalidate your changes here. That PR would allow us to pass in the video's url and have the addon sort it out as opposed to doing it here.

**Comment by xdumaine** [comment]
Changes have been separated into different PRs. What's the embedding issue you mentioned on twitter? I assumed it was this, before I found your PR to ember-lazy-load, but that assumes to solve it.

**Comment by Dhaulagiri** [comment]
I'll leave this open for now until things get sorted out in `ember-lazy-video`.  I like your approach here in the event it is needed.

**Comment by Dhaulagiri** [comment]
My PR in ember-lazy-video got merged, so I am going to close this.  Thanks for taking a look at this though!

**Pull request closed without merging**
